#1. Pandas Problem

## Basic Exploration
Load the dataset into a Pandas DataFrame. Display:


○ The first 10 rows


○ The total number of rows and columns


○ Summary statistics for numerical columns

In [206]:
import pandas as pd


In [207]:
data = pd.read_csv('auto-mpg.csv')

In [208]:
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [209]:
data.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

In [210]:
data.shape

(398, 9)

In [211]:
data.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

## 2. Filtering and Indexing
Find all cars manufactured in 1975 with a weight less than 3000. Return the
DataFrame with selected columns: car_name, weight, and mpg.

In [212]:
less_weight = data['weight'] < 3000

In [213]:
data[less_weight]

mpg  cylinders  displacement horsepower  weight  acceleration  \
14   24.0          4         113.0         95    2372          15.0   
15   22.0          6         198.0         95    2833          15.5   
16   18.0          6         199.0         97    2774          15.5   
17   21.0          6         200.0         85    2587          16.0   
18   27.0          4          97.0         88    2130          14.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin               car name  
14           70       3  toyota corona mark ii  
15           70       1        plymouth duster  
16           70       1             amc hornet  
17           70       1          ford maverick  
18           70       3           datsun pl510  
..          ...     ...                    ...  
393          82       1        ford mustang gl  
394          82       2              vw pickup  
395          82       1          dodge rampage  
396          82       1            ford ranger  
397          82       1             chevy s-10  

[230 rows x 9 columns]

In [214]:
filtered_data = data[(data['model year']== 75) & (data['weight']< 3000)]
filtered_data

mpg  cylinders  displacement horsepower  weight  acceleration  \
167  29.0          4          97.0         75    2171          16.0   
168  23.0          4         140.0         83    2639          17.0   
169  20.0          6         232.0        100    2914          16.0   
170  23.0          4         140.0         78    2592          18.5   
171  24.0          4         134.0         96    2702          13.5   
172  25.0          4          90.0         71    2223          16.5   
173  24.0          4         119.0         97    2545          17.0   
174  18.0          6         171.0         97    2984          14.5   
175  29.0          4          90.0         70    1937          14.0   
177  23.0          4         115.0         95    2694          15.0   
178  23.0          4         120.0         88    2957          17.0   
179  22.0          4         121.0         98    2945          14.5   
180  25.0          4         121.0        115    2671          13.5   
181  33.0          4          91.0         53    1795          17.5   

     model year  origin           car name  
167          75       3     toyota corolla  
168          75       1         ford pinto  
169          75       1        amc gremlin  
170          75       1      pontiac astro  
171          75       3      toyota corona  
172          75       2  volkswagen dasher  
173          75       3         datsun 710  
174          75       1         ford pinto  
175          75       2  volkswagen rabbit  
177          75       2         audi 100ls  
178          75       2        peugeot 504  
179          75       2        volvo 244dl  
180          75       2          saab 99le  
181          75       3   honda civic cvcc

In [215]:
result_data = filtered_data[['car name','weight','mpg']]
result_data

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

## 3.Handling Missing Data
Identify if there are any missing values in the dataset. Replace missing values in the
horsepower column with the column's median.

In [216]:
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [217]:
import numpy as np

In [218]:
data.replace('?',np.nan,inplace = True)

In [219]:
data['horsepower'] = pd.to_numeric(data['horsepower'],errors= 'coerce')

In [220]:
data.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [221]:
median_hp = data['horsepower'].median()

In [222]:
data['horsepower'].fillna(median_hp,inplace = True)

/tmp/ipython-input-1783760947.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['horsepower'].fillna(median_hp,inplace = True)


In [223]:
data['horsepower']

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

## 4. Data Transformation
Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [224]:
data['power_to_weight_ratio'] = data['horsepower']/data['weight']

In [225]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  
0          70       1  chevrolet chevelle malibu               0.037100  
1          70       1          buick skylark 320               0.044679  
2          70       1         plymouth satellite               0.043655  
3          70       1              amc rebel sst               0.043694  
4          70       1                ford torino               0.040591

## 5. Group By
Group the cars by origin and calculate the mean mpg for each group.

In [226]:
g= data.groupby('origin')

In [227]:
g

In [228]:
g['mpg'].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

## 6.Sorting
Sort the DataFrame by mpg in descending order and display the top 10 cars with
the highest mpg.

In [229]:
data.sort_values(by='mpg',ascending = False)[['car name','mpg']][0:10]

car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4

##7. Apply Function
Create a new column performance_score using a custom function:

Apply this function to each row and store the result in the new column.

In [230]:
def performance_score(row):
  return row['mpg'] * row['acceleration'] / row['weight']

In [231]:
data['performance_score'] = data.apply(performance_score,axis=1)

In [232]:
data.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model year  origin                   car name  power_to_weight_ratio  \
0          70       1  chevrolet chevelle malibu               0.037100   
1          70       1          buick skylark 320               0.044679   
2          70       1         plymouth satellite               0.043655   
3          70       1              amc rebel sst               0.043694   
4          70       1                ford torino               0.040591   

   performance_score  
0           0.061644  
1           0.046710  
2           0.057625  
3           0.055928  
4           0.051754

## 8. Visualization Preparation
Generate a summary DataFrame with:
○ Average mpg, weight, and horsepower for each model_year.

In [233]:
summary_data = data.groupby('model year')

In [234]:
summary_data

In [235]:
summary_data[['mpg','weight','horsepower']].mean()

mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

## 9. Exporting Data
Save a subset of the data containing only mpg, cylinders, horsepower, and weight
for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [236]:
high_mpg_cars = data['mpg'] > 30
data[high_mpg_cars][['mpg','cylinders','horsepower','weight']]

mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]

In [237]:
high_mpg_cars.to_csv('high_mpg_cars.csv',index = False)

##  10. Finding Anomalies

Identify potential outliers in the mpg column using the Interquartile Range (IQR)
method. Specifically:


● Calculate the IQR for mpg.

● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 +
1.5 * IQR.


● Create a DataFrame of cars classified as outliers, displaying car_name, mpg,
and model_year.

In [238]:
Q1 = data['mpg'].quantile(0.25)
Q3 = data['mpg'].quantile(0.75)
IQR = Q3 - Q1
print(f'\n lower Quartile is',Q1)
print(f'\n upper Quartle is',Q3)
print('\n IQR is',IQR)



 lower Quartile is 17.5

 upper Quartle is 29.0

 IQR is 11.5


In [239]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
print(f'\n lower bound is',lower_bound)
print(f'\n upper bound is',upper_bound)


 lower bound is 0.25

 upper bound is 46.25


In [240]:
outlier_data = data[(data['mpg'] < lower_bound) | (data['mpg']> upper_bound)][['car name','mpg','model year']]

In [241]:
outlier_data

car name   mpg  model year
322  mazda glc  46.6          80

#**NumPy Problems**


1 Basic Array Operations
Convert the mpg column into a NumPy array and calculate:

○ The mean, median, and standard deviation of mpg.

○ The number of cars with mpg greater than 25.

In [242]:
import numpy as np

In [243]:
mpg_array = data['mpg'].to_numpy()

In [244]:
mpg_array

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [245]:
mpg_mean = np.mean(mpg_array)

In [246]:
mpg_median = np.median(mpg_array)

In [247]:
mpg_std_deviation = np.std(mpg_array)

In [248]:
print(f'\n mean of mpg is',mpg_mean)
print(f'\n median of mpg is',mpg_median)
print(f'\n standard deviation of mpg is',mpg_std_deviation)


 mean of mpg is 23.514572864321607

 median of mpg is 23.0

 standard deviation of mpg is 7.806159061274433


In [249]:
count_high_mpg_cars = np.sum(mpg_array > 25)
print(f'\n number of cars with mpg greater than 25 is:',count_high_mpg_cars)


 number of cars with mpg greater than 25 is: 158


## 2. Filtering
Using NumPy, filter all cars with more than 6 cylinders.


Return the corresponding car_name as a list.

In [250]:
cylinders_array = data['cylinders'].to_numpy()


In [251]:
cylinders_array


array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 6, 6, 6, 4, 4, 4, 4,
       4, 4, 6, 8, 8, 8, 8, 4, 4, 4, 4, 6, 6, 6, 6, 6, 8, 8, 8, 8, 8, 8,
       8, 6, 4, 6, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, 4, 8, 8, 8, 8, 6, 4, 4,
       4, 3, 4, 6, 4, 8, 8, 4, 4, 4, 4, 8, 4, 6, 8, 6, 6, 6, 6, 4, 4, 4,
       4, 6, 6, 6, 8, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6,
       6, 6, 8, 8, 8, 8, 6, 6, 6, 6, 6, 8, 8, 4, 4, 6, 4, 4, 4, 4, 6, 4,
       6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 6, 6, 6, 6, 4, 4, 4,
       4, 6, 6, 6, 6, 4, 4, 4, 4, 4, 8, 4, 6, 6, 8, 8, 8, 8, 4, 4, 4, 4,
       4, 8, 8, 8, 8, 6, 6, 6, 6, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 6,
       4, 3, 4, 4, 4, 4, 4, 8, 8, 8, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 8, 6,
       8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6, 4, 6, 4, 4, 6, 6, 4, 6, 6, 8,
       8, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 5, 8, 4, 8,

In [252]:
mask = cylinders_array > 6  # Create a boolean mask for cars with more than 6 cylinders



In [253]:
carname_array = data['car name'].to_numpy()[mask]   ## Apply the mask to get corresponding car names

In [254]:
car_names = carname_array.tolist()

In [255]:
print(car_names)

['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino', 'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii', 'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se', "plymouth 'cuda 340", 'chevrolet monte carlo', 'buick estate wagon (sw)', 'ford f250', 'chevy c20', 'dodge d200', 'hi 1200d', 'chevrolet impala', 'pontiac catalina brougham', 'ford galaxie 500', 'plymouth fury iii', 'dodge monaco (sw)', 'ford country squire (sw)', 'pontiac safari (sw)', 'chevrolet impala', 'pontiac catalina', 'plymouth fury iii', 'ford galaxie 500', 'amc ambassador sst', 'mercury marquis', 'buick lesabre custom', 'oldsmobile delta 88 royale', 'chrysler newport royal', 'amc matador (sw)', 'chevrolet chevelle concours (sw)', 'ford gran torino (sw)', 'plymouth satellite custom (sw)', 'buick century 350', 'amc matador', 'chevrolet malibu', 'ford gran torino', 'dodge coronet custom', 'mercury marquis brougham', 'chevrolet caprice classic', 'ford l

##2.  Statistical Analysis
Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.

In [256]:
weight_array = data['weight'].to_numpy()

In [257]:
weight_array

array([3504, 3693, 3436, 3433, 3449, 4341, 4354, 4312, 4425, 3850, 3563,
       3609, 3761, 3086, 2372, 2833, 2774, 2587, 2130, 1835, 2672, 2430,
       2375, 2234, 2648, 4615, 4376, 4382, 4732, 2130, 2264, 2228, 2046,
       2634, 3439, 3329, 3302, 3288, 4209, 4464, 4154, 4096, 4955, 4746,
       5140, 2962, 2408, 3282, 3139, 2220, 2123, 2074, 2065, 1773, 1613,
       1834, 1955, 2278, 2126, 2254, 2408, 2226, 4274, 4385, 4135, 4129,
       3672, 4633, 4502, 4456, 4422, 2330, 3892, 4098, 4294, 4077, 2933,
       2511, 2979, 2189, 2395, 2288, 2506, 2164, 2100, 4100, 3672, 3988,
       4042, 3777, 4952, 4464, 4363, 4237, 4735, 4951, 3821, 3121, 3278,
       2945, 3021, 2904, 1950, 4997, 4906, 4654, 4499, 2789, 2279, 2401,
       2379, 2124, 2310, 2472, 2265, 4082, 4278, 1867, 2158, 2582, 2868,
       3399, 2660, 2807, 3664, 3102, 2875, 2901, 3336, 1950, 2451, 1836,
       2542, 3781, 3632, 3613, 4141, 4699, 4457, 4638, 4257, 2219, 1963,
       2300, 1649, 2003, 2125, 2108, 2246, 2489, 23

In [258]:
percentile_25 = np.percentile(weight_array,25)
percentile_50 = np.percentile(weight_array,50)
percentile_75 = np.percentile(weight_array,75)

In [259]:
print(f'\n 25th percentile of weight is',percentile_25)
print(f'\n 50th percentile of weight is',percentile_50)
print(f'\n 75th percentile of weight is',percentile_75)



 25th percentile of weight is 2223.75

 50th percentile of weight is 2803.5

 75th percentile of weight is 3608.0


## 3. Array Manipulation
Convert the acceleration column into a NumPy array and normalize its values
(scale between 0 and 1).

In [260]:
accelaration_array = data['acceleration'].to_numpy()

In [261]:
accelaration_min = np.min(accelaration_array)
accelaration_max = np.max(accelaration_array)
accelaration_norm =  (accelaration_array - accelaration_min) /(accelaration_max-accelaration_min)


In [262]:
print(f'\n the normalised value is given by formula[ x-min(x)]/[max(x)-min(x)]',accelaration_norm)


 the normalised value is given by formula[ x-min(x)]/[max(x)-min(x)] [0.23809524 0.20833333 0.17857143 0.23809524 0.14880952 0.11904762
 0.05952381 0.0297619  0.11904762 0.0297619  0.11904762 0.
 0.08928571 0.11904762 0.41666667 0.44642857 0.44642857 0.47619048
 0.38690476 0.74404762 0.56547619 0.38690476 0.56547619 0.26785714
 0.41666667 0.35714286 0.41666667 0.32738095 0.625      0.38690476
 0.44642857 0.35714286 0.6547619  0.29761905 0.44642857 0.44642857
 0.44642857 0.44642857 0.23809524 0.20833333 0.32738095 0.29761905
 0.20833333 0.23809524 0.23809524 0.32738095 0.6547619  0.41666667
 0.38690476 0.35714286 0.35714286 0.68452381 0.38690476 0.6547619
 0.5952381  0.6547619  0.74404762 0.44642857 0.53571429 0.92261905
 0.68452381 0.50595238 0.23809524 0.23809524 0.32738095 0.29761905
 0.20833333 0.17857143 0.32738095 0.32738095 0.26785714 0.32738095
 0.26785714 0.35714286 0.47619048 0.35714286 0.38690476 0.5952381
 0.68452381 0.5952381  0.47619048 0.53571429 0.38690476 0.41666667
 0

## 5. Broadcasting
Increase all horsepower values by 10% and store the updated values in a new
NumPy array. Handle missing data (if any) by replacing it with the mean of the
column before applying the increase.

In [263]:
horsepower_array = data['horsepower'].to_numpy()

In [264]:
new_horsepower = horsepower_array *1.10

In [265]:
new_horsepower

array([143.  , 181.5 , 165.  , 165.  , 154.  , 217.8 , 242.  , 236.5 ,
       247.5 , 209.  , 187.  , 176.  , 165.  , 247.5 , 104.5 , 104.5 ,
       106.7 ,  93.5 ,  96.8 ,  50.6 ,  95.7 ,  99.  , 104.5 , 124.3 ,
        99.  , 236.5 , 220.  , 231.  , 212.3 ,  96.8 ,  99.  , 104.5 ,
       102.85, 110.  , 115.5 , 110.  ,  96.8 , 110.  , 181.5 , 192.5 ,
       168.3 , 165.  , 198.  , 187.  , 192.5 , 121.  ,  79.2 , 110.  ,
        96.8 ,  94.6 ,  99.  ,  77.  ,  83.6 ,  71.5 ,  75.9 ,  66.  ,
        77.  , 104.5 ,  88.  ,  59.4 ,  99.  ,  94.6 , 181.5 , 192.5 ,
       165.  , 168.3 , 165.  , 228.8 , 170.5 , 176.  , 209.  , 106.7 ,
       165.  , 143.  , 154.  , 165.  , 123.2 ,  83.6 ,  95.7 ,  75.9 ,
        94.6 , 101.2 , 106.7 ,  88.  ,  96.8 , 192.5 , 165.  , 159.5 ,
       150.7 , 165.  , 217.8 , 165.  , 173.8 , 165.  , 236.5 , 247.5 ,
       192.5 , 115.5 , 110.  , 110.  ,  96.8 , 104.5 ,  50.6 , 165.  ,
       183.7 , 187.  , 198.  , 110.  ,  96.8 ,  79.2 , 103.4 ,  99.  ,
      

## 6. Boolean Indexing
Find the average displacement of cars with an origin of 2 (Europe) using NumPy
indexing.

In [266]:
displacement_array = data['displacement'].to_numpy()
displacement_array

array([307. , 350. , 318. , 304. , 302. , 429. , 454. , 440. , 455. ,
       390. , 383. , 340. , 400. , 455. , 113. , 198. , 199. , 200. ,
        97. ,  97. , 110. , 107. , 104. , 121. , 199. , 360. , 307. ,
       318. , 304. ,  97. , 140. , 113. ,  98. , 232. , 225. , 250. ,
       250. , 232. , 350. , 400. , 351. , 318. , 383. , 400. , 400. ,
       258. , 140. , 250. , 250. , 122. , 116. ,  79. ,  88. ,  71. ,
        72. ,  97. ,  91. , 113. ,  97.5,  97. , 140. , 122. , 350. ,
       400. , 318. , 351. , 304. , 429. , 350. , 350. , 400. ,  70. ,
       304. , 307. , 302. , 318. , 121. , 121. , 120. ,  96. , 122. ,
        97. , 120. ,  98. ,  97. , 350. , 304. , 350. , 302. , 318. ,
       429. , 400. , 351. , 318. , 440. , 455. , 360. , 225. , 250. ,
       232. , 250. , 198. ,  97. , 400. , 400. , 360. , 350. , 232. ,
        97. , 140. , 108. ,  70. , 122. , 155. ,  98. , 350. , 400. ,
        68. , 116. , 114. , 121. , 318. , 121. , 156. , 350. , 198. ,
       200. , 232. ,

In [267]:
origin_array = data['origin'].to_numpy()
origin_array

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 2, 2, 2,
       2, 2, 1, 1, 1, 1, 1, 3, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 2, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 2, 2, 2, 1, 3, 3, 1, 3, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 1,
       3, 3, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 3, 1, 1, 1, 1, 1, 3, 1, 3,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 1, 2, 2, 3, 3, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 3, 2, 3, 1, 2,
       1, 2, 2, 2, 2, 3, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       3, 1, 1, 1, 1, 2, 3, 3, 1, 2, 1, 2, 3, 2, 1, 1, 1, 1, 3, 1, 2, 1,
       3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 3, 2, 3,
       2, 3, 2, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 3, 3, 1, 3, 1, 1, 3, 2, 2, 2, 2, 2, 3, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, 2, 1,

In [268]:
europe_cars = np.where(origin_array == 2)     #indexing of origin
europe_cars

(array([ 19,  20,  21,  22,  23,  50,  51,  52,  55,  59,  76,  77,  78,
         79, 102, 114, 117, 118, 119, 120, 122, 141, 142, 143, 147, 148,
        151, 172, 175, 177, 178, 179, 180, 182, 183, 186, 197, 203, 207,
        209, 211, 218, 233, 240, 242, 244, 274, 275, 276, 277, 278, 293,
        297, 299, 304, 309, 317, 325, 326, 327, 328, 330, 332, 335, 353,
        354, 359, 360, 375, 394]),)

In [269]:
displacements = displacement_array[europe_cars]
displacements

array([ 97., 110., 107., 104., 121., 116.,  79.,  88.,  97.,  97., 121.,
       121., 120.,  96.,  97.,  98.,  68., 116., 114., 121., 121.,  98.,
        79.,  97.,  90., 116.,  79.,  90.,  90., 115., 120., 121., 121.,
       107., 116., 101.,  90.,  97., 130., 120., 168.,  79.,  97.,  97.,
       121.,  90., 131., 163., 121., 163.,  89.,  89., 183., 141.,  91.,
        98.,  97.,  90.,  90., 121., 146.,  85.,  89., 122., 105., 100.,
       141., 145., 105.,  97.])

In [270]:
average_displacement = np.mean(displacements)

In [271]:
print ('Average displacement of European cars is  ',average_displacement)

Average displacement of European cars is   109.14285714285714


## Matrix Operations
Create a 2D NumPy array containing the columns mpg, horsepower, and weight.
Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [272]:
mpg_array = data['mpg'].to_numpy()

In [273]:
horsepower_array = data['horsepower'].to_numpy()

In [274]:
weight_array = data['weight'].to_numpy()

In [275]:
matrix = np.array([[mpg_array],[horsepower_array],[weight_array]])

In [276]:
new_matrix = matrix.T

In [277]:
new_matrix

array([[[  18.,  130., 3504.]],

       [[  15.,  165., 3693.]],

       [[  18.,  150., 3436.]],

       ...,

       [[  32.,   84., 2295.]],

       [[  28.,   79., 2625.]],

       [[  31.,   82., 2720.]]])

In [278]:
vector = np.array([1, 0.5, -0.2])

In [279]:
vector

array([ 1. ,  0.5, -0.2])

In [280]:
dot_product = np.dot(new_matrix, vector)

In [281]:
dot_product

array([[-617.8 ],
       [-641.1 ],
       [-594.2 ],
       [-595.6 ],
       [-602.8 ],
       [-754.2 ],
       [-746.8 ],
       [-740.9 ],
       [-758.5 ],
       [-660.  ],
       [-612.6 ],
       [-627.8 ],
       [-662.2 ],
       [-490.7 ],
       [-402.9 ],
       [-497.1 ],
       [-488.3 ],
       [-453.9 ],
       [-355.  ],
       [-318.  ],
       [-465.9 ],
       [-417.  ],
       [-402.5 ],
       [-364.3 ],
       [-463.6 ],
       [-805.5 ],
       [-765.2 ],
       [-760.4 ],
       [-840.9 ],
       [-355.  ],
       [-379.8 ],
       [-373.1 ],
       [-337.45],
       [-457.8 ],
       [-619.3 ],
       [-598.8 ],
       [-597.4 ],
       [-589.6 ],
       [-745.3 ],
       [-791.3 ],
       [-740.3 ],
       [-730.2 ],
       [-889.  ],
       [-851.2 ],
       [-927.5 ],
       [-519.4 ],
       [-423.6 ],
       [-587.4 ],
       [-565.8 ],
       [-378.  ],
       [-351.6 ],
       [-349.8 ],
       [-345.  ],
       [-291.1 ],
       [-253.1 ],
       [-3

## 8. Sorting
Use NumPy to sort the cars by model_year in descending order and display the first
f
ive car names.

In [282]:
modelyear_array = data['model year'].to_numpy()
carname_array = data['car name'].to_numpy()

In [283]:
sorted_array = np.sort(modelyear_array)[::-1]
sorted_array

array([82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82,
       82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 82, 81, 81, 81,
       81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81, 81,
       81, 81, 81, 81, 81, 81, 81, 81, 81, 80, 80, 80, 80, 80, 80, 80, 80,
       80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80,
       80, 80, 80, 80, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79,
       79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 79, 78,
       78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78,
       78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78, 78,
       78, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77,
       77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 76, 76, 76, 76, 76,
       76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76,
       76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 75, 75, 75, 75, 75,
       75, 75, 75, 75, 75

In [284]:
top_cars = carname_array[sorted_array][0:5]
top_cars

array(['toyouta corona mark ii (sw)', 'toyouta corona mark ii (sw)',
       'toyouta corona mark ii (sw)', 'toyouta corona mark ii (sw)',
       'toyouta corona mark ii (sw)'], dtype=object)

In [285]:
print('top 5 latest cars: ')
for name in top_cars:
  print(name)

top 5 latest cars: 
toyouta corona mark ii (sw)
toyouta corona mark ii (sw)
toyouta corona mark ii (sw)
toyouta corona mark ii (sw)
toyouta corona mark ii (sw)


## 9. Correlation
Compute the Pearson correlation coefficient between mpg and weight using
NumPy.

In [286]:
data = np.genfromtxt('auto-mpg.csv', delimiter=',', skip_header=1)

In [287]:
mpg = data[:,0]
weight = data[:,4]

In [288]:
correlation_matrix = np.corrcoef(mpg,weight) # np.corrcoef() returns correlation matrix

In [289]:
pearson_coef = correlation_matrix[0, 1]

In [290]:
print ('Pearson coefficient is ', pearson_coef)

Pearson coefficient is  -0.8317409332443352


## 10.  Conditional Aggregates
Calculate the mean mpg for cars grouped by the number of cylinders using NumPy
techniques.

In [291]:
unique_cylinders = np.unique(cylinders_array)
unique_cylinders

array([3, 4, 5, 6, 8])

In [292]:
for c in unique_cylinders:
  mpg_mean = np.mean(mpg_array[cylinders_array == c])
  print(f'Cylinders :{c}, mean mpg is {mpg_mean}')

Cylinders :3, mean mpg is 20.55
Cylinders :4, mean mpg is 29.28676470588235
Cylinders :5, mean mpg is 27.366666666666664
Cylinders :6, mean mpg is 19.985714285714284
Cylinders :8, mean mpg is 14.963106796116506
